# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Hate in America"
description: "News21 investigates how hate is changing a nation"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://voting.countzero.xyz" # the base hostname & protocol for your site
#url: "https://hate.countzero.xyz"
destination: "_site"
#destination: /var/www/votingwars/

publishdate: "Saturday, Aug. 20, 2016"

# Build settings
sass:
  style: compressed

collections:
  stories:
    output: true

markdown: kramdown

exclude: ['README.md', 'Gemfile']

gems:
  - jekyll-seo-tag

# # jekyll-seo-tag settings
# twitter:
#   username: news21
# image: /img/social/votingwars.jpg